package app.eduroam.geteduroam.ui.theme

import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFF00668b)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFc3e7ff)
val md_theme_light_onPrimaryContainer = Color(0xFF001e2d)
val md_theme_light_secondary = Color(0xFF00668b)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFc2e8ff)
val md_theme_light_onSecondaryContainer = Color(0xFF001e2c)
val md_theme_light_tertiary = Color(0xFFec446c)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFffd9de)
val md_theme_light_onTertiaryContainer = Color(0xFF400011)
val md_theme_light_error = Color(0xFFB3261E)
val md_theme_light_errorContainer = Color(0xFFF9DEDC)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410E0B)
val md_theme_light_background = Color(0xFFfbfdf7)
val md_theme_light_onBackground = Color(0xFF1a1c1a)
val md_theme_light_surface = Color(0xFFfbfdf7)
val md_theme_light_onSurface = Color(0xFF1a1c1a)
val md_theme_light_surfaceVariant = Color(0xFFE7E0EC)
val md_theme_light_onSurfaceVariant = Color(0xFF49454F)
val md_theme_light_outline = Color(0xFF79747E)
val md_theme_light_inverseOnSurface = Color(0xFFf0f1ec)
val md_theme_light_inverseSurface = Color(0xFF2e312e)
val md_theme_light_inversePrimary = Color(0xFF7ad0ff)
val md_theme_light_shadow = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF7ad0ff)
val md_theme_dark_onPrimary = Color(0xFF00344a)
val md_theme_dark_primaryContainer = Color(0xFF004c6a)
val md_theme_dark_onPrimaryContainer = Color(0xFFc3e7ff)
val md_theme_dark_secondary = Color(0xFF77d1ff)
val md_theme_dark_onSecondary = Color(0xFF003549)
val md_theme_dark_secondaryContainer = Color(0xFF004c69)
val md_theme_dark_onSecondaryContainer = Color(0xFFc2e8ff)
val md_theme_dark_tertiary = Color(0xFFffb2bd)
val md_theme_dark_onTertiary = Color(0xFF670020)
val md_theme_dark_tertiaryContainer = Color(0xFF910031)
val md_theme_dark_onTertiaryContainer = Color(0xFFffd9de)
val md_theme_dark_error = Color(0xFFF2B8B5)
val md_theme_dark_errorContainer = Color(0xFF8C1D18)
val md_theme_dark_onError = Color(0xFF601410)
val md_theme_dark_onErrorContainer = Color(0xFFF9DEDC)
val md_theme_dark_background = Color(0xFF1a1c1a)
val md_theme_dark_onBackground = Color(0xFFe2e3de)
val md_theme_dark_surface = Color(0xFF1a1c1a)
val md_theme_dark_onSurface = Color(0xFFe2e3de)
val md_theme_dark_surfaceVariant = Color(0xFF49454F)
val md_theme_dark_onSurfaceVariant = Color(0xFFCAC4D0)
val md_theme_dark_outline = Color(0xFF938F99)
val md_theme_dark_inverseOnSurface = Color(0xFF1a1c1a)
val md_theme_dark_inverseSurface = Color(0xFFe2e3de)
val md_theme_dark_inversePrimary = Color(0xFF00668b)
val md_theme_dark_shadow = Color(0xFF000000)


val seed = Color(0xFF6750A4)
val error = Color(0xFFB3261E)